....

diff --git a/.github/workflows/sonatype_v2.yml b/.github/workflows/sonatype_v2.yml
--- a/.github/workflows/sonatype_v2.yml
+++ b/.github/workflows/sonatype_v2.yml
@@ -8,6 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up Maven Central Repository
         uses: actions/setup-java@v4
         with:
@@ -17,15 +18,25 @@ jobs:
           server-username: ${{ vars.MVN_CENTRAL_USERNAME }}
           server-password: ${{ secrets.MVN_CENTRAL_PASSWORD }}
           gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
-          gpg-passphrase: Escol@1979270881
+          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}  # Use segredo para passphrase
+
+      # Adicionando um passo de debug para verificar a chave GPG
+      - name: Debug GPG Key
+        run: |
+          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private_key.asc
+          gpg --batch --import private_key.asc || (echo "Failed to import GPG key" && exit 1)
+        env:
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+
       - name: Display modified settings.xml
         run: cat ~/.m2/settings.xml
+
       - name: Set version
-        run: |
-          mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
+        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
+
       - name: Publish package
-        run: ls
+        run: mvn deploy -P release -s /home/runner/.m2/settings.xml
         env:
           MAVEN_USERNAME: ${{ vars.MVN_CENTRAL_USERNAME }}
           MAVEN_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
-          MAVEN_GPG_PASSPHRASE: Escol@1979270881
+          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}  # Use segredo para passphrase
